import type { Metadata } from "next";
import { Playfair_Display} from "next/font/google";
import "./globals.css";
import Provider from "./_components/Provider";
import { ClerkProvider } from "@clerk/nextjs";
import { ConvexClientProvider } from "./ConvexClientProvider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const playfair_display =  Playfair_Display({subsets:['latin']})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log(
  "PUB KEY =",
  process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
);
  return (
    <ClerkProvider>
    <html
      lang="en">
      <body className={playfair_display.className}>
  <ConvexClientProvider>
    <Provider>
      {children}
    </Provider>
  </ConvexClientProvider>
</body>
       
 
       
        
        
    </html>
    </ClerkProvider>
  );
}
